version: "1.0"
# 用于将写好的的全部程序打包进镜像中即code data notebook中的文件全部在dockfile中打包进镜像了
# 因此这里在运行镜像时，就没有必要再挂载data code notebook了
# 修改command 作为启动容器时的运行命令 
services:
  xyz/python:       
    build: 
      dockerfile: ./docker/Dockerfile-prod
      context: ./
    image: xyz/python 
    #env_file: 
    #  - .env_prod

    command: 
      python /code/example.py

  
    #volumes:
    #  - /real_data_location:/data